{
 "title": "internet connection",
 "tags": [
  "speedtest",
  "ping"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Download speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(speedtest_download_bytes{server_id=\"30906\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bytes{server_id=\"30906\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_latency_seconds{server_id=\"30906\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "speedtest",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "speedtest_download_bytes{server_id=\"30906\"}",
     "legendFormat": "Download speed"
    },
    {
     "expr": "speedtest_upload_bytes{server_id=\"30906\"}",
     "legendFormat": "Upload speed"
    }
   ]
  },
  {
   "title": "p95 ping",
   "type": "timeseries",
   "description": "10min rollup",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95, probe_duration_seconds{humanname=~\"8.8.8.8|fritz.box\"}[10m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}